name: Cypress Cloud

on: 
  workflow_dispatch:
    inputs:
      spec:
        description: Run by cypress command line
        default: cypress/e2e/*
jobs:
  cypress-e2s-electron:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome107
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v3.5.2
        
      - name: Cypress run
        uses: cypress-io/github-action@v5.7.2
        with:
          install-command: yarn install
          browser: electron 
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: 38c172ac-7a46-47e6-8912-75dda66071b3
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  cypress-e2e-chrome:
      needs: cypress-e2s-electron
      runs-on: ubuntu-latest
      container:
        image: cypress/browsers:node18.12.0-chrome107
        options: --user 1001
      steps:
       - name: Get code
         uses: actions/checkout@v3.5.2
        
       - name: Cypress run
         uses: cypress-io/github-action@v5.7.2
         with:
            install-command: yarn install
            browser: chrome 
            record: true
            group: UI Chrome
            spec: ${{ github.event.inputs.spec }}
         env:
            CYPRESS_RECORD_KEY: 38c172ac-7a46-47e6-8912-75dda66071b3
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  cypress-e2e-firefox:
      needs: cypress-e2e-chrome
      runs-on: ubuntu-latest
      container:
        image: cypress/browsers:node18.12.0-chrome107
        options: --user 1001
      steps:
        - name: Get code
          uses: actions/checkout@v3.5.2
        
        - name: Cypress run
          uses: cypress-io/github-action@v5.7.2
          with:
            install-command: yarn install
            browser: firefox 
            record: true
            group: UI Firifox
            spec: ${{ github.event.inputs.spec }}
          env:
            CYPRESS_RECORD_KEY: 38c172ac-7a46-47e6-8912-75dda66071b3
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
  
  
