name: Cypress Tests

on: 
  workflow_dispatch:
    
jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome107
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v3.5.2
        
      - name: Install dependencies
        run: yarn install
        
      - name: Run E2E tests
        run: node runner-electron.js
    env:
      TARER_TOKEN_ELECTRON: ${{ secrets.TARER_TOKEN_ELECTRON }}
  cypress-chrome-tests:
    needs: cypress-electron-tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome107
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v3.5.2
        
      - name: Install dependencies
        run: yarn install
        
      - name: Run E2E tests
        run: node runner-electron.js
    env:
      TARER_TOKEN_CHROME: ${{ secrets.TARER_TOKEN_CHROME }}
